package com.zcshou.runnerprobe.service;

public enum RecordingError {
    NONE,
    PERMISSION_DENIED,
    SENSOR_ABSENT,
    SENSOR_PRESENT_NO_EVENTS,
    COUNTER_DISCONTINUITY,
    TRACE_WRITE_FAILURE,
    TRACE_CLOSE_TIMEOUT,
    TRACE_CLOSE_FAILURE,
    SESSION_START_FAILURE,
    SESSION_ID_ALREADY_EXISTS,
    NOT_READY,
    INVALID_SENSOR_VALUE,
    SESSION_INTERRUPTED
}
